2015-01-29 15:40:13,140 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 15:41:38,631 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 15:47:09,521 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 15:50:22,804 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 15:50:42,144 ERROR: Exception on /edit [GET] [in /usr/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/mattsona/Documents/Python/mega-1/app/views.py", line 95, in edit
    form = EditForm()
  File "/usr/local/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
2015-01-29 15:54:11,070 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 15:57:26,192 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 15:57:34,829 ERROR: Exception on /edit [GET] [in /usr/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/mattsona/Documents/Python/mega-1/app/views.py", line 95, in edit
    form = EditForm()
  File "/usr/local/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
2015-01-29 16:00:16,046 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 17:00:31,706 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 17:01:27,583 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 17:10:55,310 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
2015-01-29 17:11:44,888 INFO: microMega startup [in /Users/mattsona/Documents/Python/mega-1/app/__init__.py:37]
